### PR TITLE
Propose different error message

### PR DESCRIPTION
**Pull request by jackbravo**
I bumped into this error while trying to open the wiki while on the settings page. It wasn't very helpful. This is as proposal, although I feel it can be improved.

### CODE REVIEW

**Comment by hannut91** [comment]
Thank you so much!
Sorry for the inconvenience, English is not my first language. 
I understand what you are trying to propose, but the error message `Current window is not and editor window.` is not clear to me. 

How about this? 
```
Current window does not support 'Go to Wiki' command. Try it in the Wiki document.
```

**Review by hannut91 — CHANGES_REQUESTED** [review]
Thank you so much!
Sorry for the inconvenience, English is not my first language. 
I understand what you are trying to propose, but the error message `Current window is not and editor window.` is not clear to me. 

How about this? 
```
Current window does not support 'Go to Wiki' command. Try it in the Wiki window.
```

**Comment by jackbravo** [comment]
I changed it to `Current window does not support "Go to Wiki" command. Try it on a regular editing window.` Because this error appears when you are not on a Wiki window. What do you think

**Review by hannut91 — APPROVED** [review]
Very nice! Thank you so much!!

**Comment by hannut91** [comment]
I released as version 0.4.8.

**Pull request merged**
